[package]
name = "FinSCRAPE"
version = "0.1.0"
authors = ["user"]
edition = "2018"

[dependencies]
reqwest = "0.9.8"
rusqlite = "0.16.0"
lettre = "0.8.3"
csv = "1.0.5"
serde_json = "1.0.36"
systemstat = "0.1.3"
serde = "1.0.84"
serde_derive = "1.0.84"
